import type { LevelProgress } from './types'

export interface LevelActor {
  characterId: string   // fixed NPC for this slot in the sequence
  // Each entry is a request stop (a POI where the NPC shows a persistent
  // request); the value is how many questions are asked at that stop.
  // e.g. [2] = one stop, 2 questions; [1,1] = two stops, 1 question each.
  requests: number[]
}

export interface Level {
  id: number
  name: string
  starThresholds: [number, number, number]   // net coins needed for 1 / 2 / 3 stars
  actors: LevelActor[]                        // fixed sequence of NPCs (exactly N customers)
}

// POC: 3 scripted levels. Same sequence of NPCs every run; only the conversation
// content varies. Star thresholds are sized to each level's total question count
// (base earning is ~1 coin per perfect answer before upgrades).
export const LEVELS: Level[] = [
  {
    id: 1,
    name: 'Morning Rush',
    starThresholds: [20, 30, 40], // 6 questions total
    actors: [
      { characterId: 'marie', requests: [2] },     // 1 stop, 2 questions
      { characterId: 'jean', requests: [1] },      // 1 stop, 1 question
      { characterId: 'lucas', requests: [1, 1] },  // 2 stops, 1 each
      { characterId: 'sophie', requests: [1] },
      { characterId: 'camille', requests: [1] },
      { characterId: 'lucas', requests: [2] },
    ],
  },
  {
    id: 2,
    name: 'Lunch Crowd',
    starThresholds: [4, 7, 10], // 10 questions total
    actors: [
      { characterId: 'marie', requests: [2] },
      { characterId: 'jean', requests: [1, 1] },
      { characterId: 'camille', requests: [1] },
      { characterId: 'lucas', requests: [2] },
      { characterId: 'pierre', requests: [1] },
      { characterId: 'manon', requests: [1, 1] },
    ],
  },
  {
    id: 3,
    name: 'Happy Hour',
    starThresholds: [7, 12, 16], // 16 questions total
    actors: [
      { characterId: 'marie', requests: [2] },
      { characterId: 'jean', requests: [1, 1] },
      { characterId: 'camille', requests: [3] },
      { characterId: 'lucas', requests: [1, 1] },
      { characterId: 'sophie', requests: [2] },
      { characterId: 'pierre', requests: [1] },
      { characterId: 'manon', requests: [1, 1] },
      { characterId: 'theo', requests: [2] },
    ],
  },
  {
    id: 4,
    name: 'Evening Glow',
    starThresholds: [3, 5, 7],
    actors: [
      { characterId: 'colette', requests: [1] },
      { characterId: 'antoine', requests: [2] },
      { characterId: 'marcel', requests: [1] },
      { characterId: 'eloise', requests: [2, 1] },
    ],
  },
  {
    id: 5,
    name: 'Late Shift',
    starThresholds: [3, 5, 7],
    actors: [
      { characterId: 'juliette', requests: [1] },
      { characterId: 'olivier', requests: [2] },
      { characterId: 'marie', requests: [1] },
      { characterId: 'lucas', requests: [2, 1] },
    ],
  },
  {
    id: 6,
    name: 'Weekend Rush',
    starThresholds: [3, 5, 7],
    actors: [
      { characterId: 'raphael', requests: [1] },
      { characterId: 'camille', requests: [2] },
      { characterId: 'pierre', requests: [1] },
      { characterId: 'amelie', requests: [2, 1] },
    ],
  },
  {
    id: 7,
    name: 'Rainy Day',
    starThresholds: [3, 6, 8],
    actors: [
      { characterId: 'sophie', requests: [1] },
      { characterId: 'theo', requests: [2] },
      { characterId: 'claire', requests: [1] },
      { characterId: 'louis', requests: [2, 1] },
      { characterId: 'remi', requests: [1] },
    ],
  },
  {
    id: 8,
    name: 'Market Day',
    starThresholds: [3, 6, 8],
    actors: [
      { characterId: 'hugo', requests: [1] },
      { characterId: 'lea', requests: [2] },
      { characterId: 'isabelle', requests: [1] },
      { characterId: 'vincent', requests: [2, 1] },
      { characterId: 'gabriel', requests: [1] },
    ],
  },
  {
    id: 9,
    name: 'Festival',
    starThresholds: [3, 6, 8],
    actors: [
      { characterId: 'nicolas', requests: [1] },
      { characterId: 'nadia', requests: [2] },
      { characterId: 'colette', requests: [1] },
      { characterId: 'antoine', requests: [2, 1] },
      { characterId: 'marcel', requests: [1] },
    ],
  },
  {
    id: 10,
    name: 'Quiet Morning',
    starThresholds: [4, 7, 10],
    actors: [
      { characterId: 'chloe', requests: [1] },
      { characterId: 'margot', requests: [2] },
      { characterId: 'juliette', requests: [1] },
      { characterId: 'olivier', requests: [2, 1] },
      { characterId: 'marie', requests: [1] },
      { characterId: 'lucas', requests: [2] },
    ],
  },
  {
    id: 11,
    name: 'Brunch Buzz',
    starThresholds: [4, 7, 10],
    actors: [
      { characterId: 'valerie', requests: [1] },
      { characterId: 'fleur', requests: [2] },
      { characterId: 'raphael', requests: [1] },
      { characterId: 'camille', requests: [2, 1] },
      { characterId: 'pierre', requests: [1] },
      { characterId: 'amelie', requests: [2] },
    ],
  },
  {
    id: 12,
    name: 'Afternoon Lull',
    starThresholds: [4, 7, 10],
    actors: [
      { characterId: 'eloise', requests: [1] },
      { characterId: 'jean', requests: [2] },
      { characterId: 'sophie', requests: [1] },
      { characterId: 'theo', requests: [2, 1] },
      { characterId: 'claire', requests: [1] },
      { characterId: 'louis', requests: [2] },
    ],
  },
  {
    id: 13,
    name: 'Tea Time',
    starThresholds: [4, 8, 11],
    actors: [
      { characterId: 'lucas', requests: [1] },
      { characterId: 'manon', requests: [2] },
      { characterId: 'hugo', requests: [1] },
      { characterId: 'lea', requests: [2, 1] },
      { characterId: 'isabelle', requests: [1] },
      { characterId: 'vincent', requests: [2] },
      { characterId: 'gabriel', requests: [1] },
    ],
  },
  {
    id: 14,
    name: 'Evening Glow',
    starThresholds: [4, 8, 11],
    actors: [
      { characterId: 'amelie', requests: [1] },
      { characterId: 'adrien', requests: [2] },
      { characterId: 'nicolas', requests: [1] },
      { characterId: 'nadia', requests: [2, 1] },
      { characterId: 'colette', requests: [1] },
      { characterId: 'antoine', requests: [2] },
      { characterId: 'marcel', requests: [1] },
    ],
  },
  {
    id: 15,
    name: 'Late Shift',
    starThresholds: [8, 13, 19],
    actors: [
      { characterId: 'louis', requests: [2] },
      { characterId: 'remi', requests: [3] },
      { characterId: 'chloe', requests: [2] },
      { characterId: 'margot', requests: [3, 2] },
      { characterId: 'juliette', requests: [2] },
      { characterId: 'olivier', requests: [3] },
      { characterId: 'marie', requests: [2] },
    ],
  },
  {
    id: 16,
    name: 'Weekend Rush',
    starThresholds: [10, 17, 24],
    actors: [
      { characterId: 'vincent', requests: [2] },
      { characterId: 'gabriel', requests: [3] },
      { characterId: 'valerie', requests: [2] },
      { characterId: 'fleur', requests: [3, 2] },
      { characterId: 'raphael', requests: [2] },
      { characterId: 'camille', requests: [3] },
      { characterId: 'pierre', requests: [2] },
      { characterId: 'amelie', requests: [3, 2] },
    ],
  },
  {
    id: 17,
    name: 'Rainy Day',
    starThresholds: [10, 17, 24],
    actors: [
      { characterId: 'antoine', requests: [2] },
      { characterId: 'marcel', requests: [3] },
      { characterId: 'eloise', requests: [2] },
      { characterId: 'jean', requests: [3, 2] },
      { characterId: 'sophie', requests: [2] },
      { characterId: 'theo', requests: [3] },
      { characterId: 'claire', requests: [2] },
      { characterId: 'louis', requests: [3, 2] },
    ],
  },
  {
    id: 18,
    name: 'Market Day',
    starThresholds: [10, 17, 24],
    actors: [
      { characterId: 'olivier', requests: [2] },
      { characterId: 'marie', requests: [3] },
      { characterId: 'lucas', requests: [2] },
      { characterId: 'manon', requests: [3, 2] },
      { characterId: 'hugo', requests: [2] },
      { characterId: 'lea', requests: [3] },
      { characterId: 'isabelle', requests: [2] },
      { characterId: 'vincent', requests: [3, 2] },
    ],
  },
  {
    id: 19,
    name: 'Festival',
    starThresholds: [10, 18, 26],
    actors: [
      { characterId: 'camille', requests: [2] },
      { characterId: 'pierre', requests: [3] },
      { characterId: 'amelie', requests: [2] },
      { characterId: 'adrien', requests: [3, 2] },
      { characterId: 'nicolas', requests: [2] },
      { characterId: 'nadia', requests: [3] },
      { characterId: 'colette', requests: [2] },
      { characterId: 'antoine', requests: [3, 2] },
      { characterId: 'marcel', requests: [2] },
    ],
  },
  {
    id: 20,
    name: 'Quiet Morning',
    starThresholds: [10, 18, 26],
    actors: [
      { characterId: 'theo', requests: [2] },
      { characterId: 'claire', requests: [3] },
      { characterId: 'louis', requests: [2] },
      { characterId: 'remi', requests: [3, 2] },
      { characterId: 'chloe', requests: [2] },
      { characterId: 'margot', requests: [3] },
      { characterId: 'juliette', requests: [2] },
      { characterId: 'olivier', requests: [3, 2] },
      { characterId: 'marie', requests: [2] },
    ],
  },
  {
    id: 21,
    name: 'Brunch Buzz',
    starThresholds: [10, 18, 26],
    actors: [
      { characterId: 'lea', requests: [2] },
      { characterId: 'isabelle', requests: [3] },
      { characterId: 'vincent', requests: [2] },
      { characterId: 'gabriel', requests: [3, 2] },
      { characterId: 'valerie', requests: [2] },
      { characterId: 'fleur', requests: [3] },
      { characterId: 'raphael', requests: [2] },
      { characterId: 'camille', requests: [3, 2] },
      { characterId: 'pierre', requests: [2] },
    ],
  },
  {
    id: 22,
    name: 'Afternoon Lull',
    starThresholds: [12, 20, 29],
    actors: [
      { characterId: 'nadia', requests: [2] },
      { characterId: 'colette', requests: [3] },
      { characterId: 'antoine', requests: [2] },
      { characterId: 'marcel', requests: [3, 2] },
      { characterId: 'eloise', requests: [2] },
      { characterId: 'jean', requests: [3] },
      { characterId: 'sophie', requests: [2] },
      { characterId: 'theo', requests: [3, 2] },
      { characterId: 'claire', requests: [2] },
      { characterId: 'louis', requests: [3] },
    ],
  },
  {
    id: 23,
    name: 'Tea Time',
    starThresholds: [12, 20, 29],
    actors: [
      { characterId: 'margot', requests: [2] },
      { characterId: 'juliette', requests: [3] },
      { characterId: 'olivier', requests: [2] },
      { characterId: 'marie', requests: [3, 2] },
      { characterId: 'lucas', requests: [2] },
      { characterId: 'manon', requests: [3] },
      { characterId: 'hugo', requests: [2] },
      { characterId: 'lea', requests: [3, 2] },
      { characterId: 'isabelle', requests: [2] },
      { characterId: 'vincent', requests: [3] },
    ],
  },
  {
    id: 24,
    name: 'Evening Glow',
    starThresholds: [12, 20, 29],
    actors: [
      { characterId: 'fleur', requests: [2] },
      { characterId: 'raphael', requests: [3] },
      { characterId: 'camille', requests: [2] },
      { characterId: 'pierre', requests: [3, 2] },
      { characterId: 'amelie', requests: [2] },
      { characterId: 'adrien', requests: [3] },
      { characterId: 'nicolas', requests: [2] },
      { characterId: 'nadia', requests: [3, 2] },
      { characterId: 'colette', requests: [2] },
      { characterId: 'antoine', requests: [3] },
    ],
  },
  {
    id: 25,
    name: 'Late Shift',
    starThresholds: [12, 22, 31],
    actors: [
      { characterId: 'jean', requests: [2] },
      { characterId: 'sophie', requests: [3] },
      { characterId: 'theo', requests: [2] },
      { characterId: 'claire', requests: [3, 2] },
      { characterId: 'louis', requests: [2] },
      { characterId: 'remi', requests: [3] },
      { characterId: 'chloe', requests: [2] },
      { characterId: 'margot', requests: [3, 2] },
      { characterId: 'juliette', requests: [2] },
      { characterId: 'olivier', requests: [3] },
      { characterId: 'marie', requests: [2] },
    ],
  },
  {
    id: 26,
    name: 'Weekend Rush',
    starThresholds: [12, 22, 31],
    actors: [
      { characterId: 'manon', requests: [2] },
      { characterId: 'hugo', requests: [3] },
      { characterId: 'lea', requests: [2] },
      { characterId: 'isabelle', requests: [3, 2] },
      { characterId: 'vincent', requests: [2] },
      { characterId: 'gabriel', requests: [3] },
      { characterId: 'valerie', requests: [2] },
      { characterId: 'fleur', requests: [3, 2] },
      { characterId: 'raphael', requests: [2] },
      { characterId: 'camille', requests: [3] },
      { characterId: 'pierre', requests: [2] },
    ],
  },
  {
    id: 27,
    name: 'Rainy Day',
    starThresholds: [12, 22, 31],
    actors: [
      { characterId: 'adrien', requests: [2] },
      { characterId: 'nicolas', requests: [3] },
      { characterId: 'nadia', requests: [2] },
      { characterId: 'colette', requests: [3, 2] },
      { characterId: 'antoine', requests: [2] },
      { characterId: 'marcel', requests: [3] },
      { characterId: 'eloise', requests: [2] },
      { characterId: 'jean', requests: [3, 2] },
      { characterId: 'sophie', requests: [2] },
      { characterId: 'theo', requests: [3] },
      { characterId: 'claire', requests: [2] },
    ],
  },
  {
    id: 28,
    name: 'Market Day',
    starThresholds: [14, 25, 36],
    actors: [
      { characterId: 'remi', requests: [2] },
      { characterId: 'chloe', requests: [3] },
      { characterId: 'margot', requests: [2] },
      { characterId: 'juliette', requests: [3, 2] },
      { characterId: 'olivier', requests: [2] },
      { characterId: 'marie', requests: [3] },
      { characterId: 'lucas', requests: [2] },
      { characterId: 'manon', requests: [3, 2] },
      { characterId: 'hugo', requests: [2] },
      { characterId: 'lea', requests: [3] },
      { characterId: 'isabelle', requests: [2] },
      { characterId: 'vincent', requests: [3, 2] },
    ],
  },
  {
    id: 29,
    name: 'Festival',
    starThresholds: [14, 25, 36],
    actors: [
      { characterId: 'gabriel', requests: [2] },
      { characterId: 'valerie', requests: [3] },
      { characterId: 'fleur', requests: [2] },
      { characterId: 'raphael', requests: [3, 2] },
      { characterId: 'camille', requests: [2] },
      { characterId: 'pierre', requests: [3] },
      { characterId: 'amelie', requests: [2] },
      { characterId: 'adrien', requests: [3, 2] },
      { characterId: 'nicolas', requests: [2] },
      { characterId: 'nadia', requests: [3] },
      { characterId: 'colette', requests: [2] },
      { characterId: 'antoine', requests: [3, 2] },
    ],
  },
  {
    id: 30,
    name: 'Quiet Morning',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'marcel', requests: [3] },
      { characterId: 'eloise', requests: [4] },
      { characterId: 'jean', requests: [3] },
      { characterId: 'sophie', requests: [4, 3] },
      { characterId: 'theo', requests: [3] },
      { characterId: 'claire', requests: [4] },
      { characterId: 'louis', requests: [3] },
      { characterId: 'remi', requests: [4, 3] },
      { characterId: 'chloe', requests: [3] },
      { characterId: 'margot', requests: [4] },
      { characterId: 'juliette', requests: [3] },
      { characterId: 'olivier', requests: [4, 3] },
    ],
  },
  {
    id: 31,
    name: 'Brunch Buzz',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'marie', requests: [3] },
      { characterId: 'lucas', requests: [4] },
      { characterId: 'manon', requests: [3] },
      { characterId: 'hugo', requests: [4, 3] },
      { characterId: 'lea', requests: [3] },
      { characterId: 'isabelle', requests: [4] },
      { characterId: 'vincent', requests: [3] },
      { characterId: 'gabriel', requests: [4, 3] },
      { characterId: 'valerie', requests: [3] },
      { characterId: 'fleur', requests: [4] },
      { characterId: 'raphael', requests: [3] },
      { characterId: 'camille', requests: [4, 3] },
    ],
  },
  {
    id: 32,
    name: 'Afternoon Lull',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'pierre', requests: [3] },
      { characterId: 'amelie', requests: [4] },
      { characterId: 'adrien', requests: [3] },
      { characterId: 'nicolas', requests: [4, 3] },
      { characterId: 'nadia', requests: [3] },
      { characterId: 'colette', requests: [4] },
      { characterId: 'antoine', requests: [3] },
      { characterId: 'marcel', requests: [4, 3] },
      { characterId: 'eloise', requests: [3] },
      { characterId: 'jean', requests: [4] },
      { characterId: 'sophie', requests: [3] },
      { characterId: 'theo', requests: [4, 3] },
    ],
  },
  {
    id: 33,
    name: 'Tea Time',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'claire', requests: [3] },
      { characterId: 'louis', requests: [4] },
      { characterId: 'remi', requests: [3] },
      { characterId: 'chloe', requests: [4, 3] },
      { characterId: 'margot', requests: [3] },
      { characterId: 'juliette', requests: [4] },
      { characterId: 'olivier', requests: [3] },
      { characterId: 'marie', requests: [4, 3] },
      { characterId: 'lucas', requests: [3] },
      { characterId: 'manon', requests: [4] },
      { characterId: 'hugo', requests: [3] },
      { characterId: 'lea', requests: [4, 3] },
    ],
  },
  {
    id: 34,
    name: 'Evening Glow',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'isabelle', requests: [3] },
      { characterId: 'vincent', requests: [4] },
      { characterId: 'gabriel', requests: [3] },
      { characterId: 'valerie', requests: [4, 3] },
      { characterId: 'fleur', requests: [3] },
      { characterId: 'raphael', requests: [4] },
      { characterId: 'camille', requests: [3] },
      { characterId: 'pierre', requests: [4, 3] },
      { characterId: 'amelie', requests: [3] },
      { characterId: 'adrien', requests: [4] },
      { characterId: 'nicolas', requests: [3] },
      { characterId: 'nadia', requests: [4, 3] },
    ],
  },
  {
    id: 35,
    name: 'Late Shift',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'colette', requests: [3] },
      { characterId: 'antoine', requests: [4] },
      { characterId: 'marcel', requests: [3] },
      { characterId: 'eloise', requests: [4, 3] },
      { characterId: 'jean', requests: [3] },
      { characterId: 'sophie', requests: [4] },
      { characterId: 'theo', requests: [3] },
      { characterId: 'claire', requests: [4, 3] },
      { characterId: 'louis', requests: [3] },
      { characterId: 'remi', requests: [4] },
      { characterId: 'chloe', requests: [3] },
      { characterId: 'margot', requests: [4, 3] },
    ],
  },
  {
    id: 36,
    name: 'Weekend Rush',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'juliette', requests: [3] },
      { characterId: 'olivier', requests: [4] },
      { characterId: 'marie', requests: [3] },
      { characterId: 'lucas', requests: [4, 3] },
      { characterId: 'manon', requests: [3] },
      { characterId: 'hugo', requests: [4] },
      { characterId: 'lea', requests: [3] },
      { characterId: 'isabelle', requests: [4, 3] },
      { characterId: 'vincent', requests: [3] },
      { characterId: 'gabriel', requests: [4] },
      { characterId: 'valerie', requests: [3] },
      { characterId: 'fleur', requests: [4, 3] },
    ],
  },
  {
    id: 37,
    name: 'Rainy Day',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'raphael', requests: [3] },
      { characterId: 'camille', requests: [4] },
      { characterId: 'pierre', requests: [3] },
      { characterId: 'amelie', requests: [4, 3] },
      { characterId: 'adrien', requests: [3] },
      { characterId: 'nicolas', requests: [4] },
      { characterId: 'nadia', requests: [3] },
      { characterId: 'colette', requests: [4, 3] },
      { characterId: 'antoine', requests: [3] },
      { characterId: 'marcel', requests: [4] },
      { characterId: 'eloise', requests: [3] },
      { characterId: 'jean', requests: [4, 3] },
    ],
  },
  {
    id: 38,
    name: 'Market Day',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'sophie', requests: [3] },
      { characterId: 'theo', requests: [4] },
      { characterId: 'claire', requests: [3] },
      { characterId: 'louis', requests: [4, 3] },
      { characterId: 'remi', requests: [3] },
      { characterId: 'chloe', requests: [4] },
      { characterId: 'margot', requests: [3] },
      { characterId: 'juliette', requests: [4, 3] },
      { characterId: 'olivier', requests: [3] },
      { characterId: 'marie', requests: [4] },
      { characterId: 'lucas', requests: [3] },
      { characterId: 'manon', requests: [4, 3] },
    ],
  },
  {
    id: 39,
    name: 'Festival',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'hugo', requests: [3] },
      { characterId: 'lea', requests: [4] },
      { characterId: 'isabelle', requests: [3] },
      { characterId: 'vincent', requests: [4, 3] },
      { characterId: 'gabriel', requests: [3] },
      { characterId: 'valerie', requests: [4] },
      { characterId: 'fleur', requests: [3] },
      { characterId: 'raphael', requests: [4, 3] },
      { characterId: 'camille', requests: [3] },
      { characterId: 'pierre', requests: [4] },
      { characterId: 'amelie', requests: [3] },
      { characterId: 'adrien', requests: [4, 3] },
    ],
  },
  {
    id: 40,
    name: 'Quiet Morning',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'nicolas', requests: [3] },
      { characterId: 'nadia', requests: [4] },
      { characterId: 'colette', requests: [3] },
      { characterId: 'antoine', requests: [4, 3] },
      { characterId: 'marcel', requests: [3] },
      { characterId: 'eloise', requests: [4] },
      { characterId: 'jean', requests: [3] },
      { characterId: 'sophie', requests: [4, 3] },
      { characterId: 'theo', requests: [3] },
      { characterId: 'claire', requests: [4] },
      { characterId: 'louis', requests: [3] },
      { characterId: 'remi', requests: [4, 3] },
    ],
  },
  {
    id: 41,
    name: 'Brunch Buzz',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'chloe', requests: [3] },
      { characterId: 'margot', requests: [4] },
      { characterId: 'juliette', requests: [3] },
      { characterId: 'olivier', requests: [4, 3] },
      { characterId: 'marie', requests: [3] },
      { characterId: 'lucas', requests: [4] },
      { characterId: 'manon', requests: [3] },
      { characterId: 'hugo', requests: [4, 3] },
      { characterId: 'lea', requests: [3] },
      { characterId: 'isabelle', requests: [4] },
      { characterId: 'vincent', requests: [3] },
      { characterId: 'gabriel', requests: [4, 3] },
    ],
  },
  {
    id: 42,
    name: 'Afternoon Lull',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'valerie', requests: [3] },
      { characterId: 'fleur', requests: [4] },
      { characterId: 'raphael', requests: [3] },
      { characterId: 'camille', requests: [4, 3] },
      { characterId: 'pierre', requests: [3] },
      { characterId: 'amelie', requests: [4] },
      { characterId: 'adrien', requests: [3] },
      { characterId: 'nicolas', requests: [4, 3] },
      { characterId: 'nadia', requests: [3] },
      { characterId: 'colette', requests: [4] },
      { characterId: 'antoine', requests: [3] },
      { characterId: 'marcel', requests: [4, 3] },
    ],
  },
  {
    id: 43,
    name: 'Tea Time',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'eloise', requests: [3] },
      { characterId: 'jean', requests: [4] },
      { characterId: 'sophie', requests: [3] },
      { characterId: 'theo', requests: [4, 3] },
      { characterId: 'claire', requests: [3] },
      { characterId: 'louis', requests: [4] },
      { characterId: 'remi', requests: [3] },
      { characterId: 'chloe', requests: [4, 3] },
      { characterId: 'margot', requests: [3] },
      { characterId: 'juliette', requests: [4] },
      { characterId: 'olivier', requests: [3] },
      { characterId: 'marie', requests: [4, 3] },
    ],
  },
  {
    id: 44,
    name: 'Evening Glow',
    starThresholds: [20, 36, 51],
    actors: [
      { characterId: 'lucas', requests: [3] },
      { characterId: 'manon', requests: [4] },
      { characterId: 'hugo', requests: [3] },
      { characterId: 'lea', requests: [4, 3] },
      { characterId: 'isabelle', requests: [3] },
      { characterId: 'vincent', requests: [4] },
      { characterId: 'gabriel', requests: [3] },
      { characterId: 'valerie', requests: [4, 3] },
      { characterId: 'fleur', requests: [3] },
      { characterId: 'raphael', requests: [4] },
      { characterId: 'camille', requests: [3] },
      { characterId: 'pierre', requests: [4, 3] },
    ],
  },
  {
    id: 45,
    name: 'Late Shift',
    starThresholds: [26, 46, 66],
    actors: [
      { characterId: 'amelie', requests: [4] },
      { characterId: 'adrien', requests: [5] },
      { characterId: 'nicolas', requests: [4] },
      { characterId: 'nadia', requests: [5, 4] },
      { characterId: 'colette', requests: [4] },
      { characterId: 'antoine', requests: [5] },
      { characterId: 'marcel', requests: [4] },
      { characterId: 'eloise', requests: [5, 4] },
      { characterId: 'jean', requests: [4] },
      { characterId: 'sophie', requests: [5] },
      { characterId: 'theo', requests: [4] },
      { characterId: 'claire', requests: [5, 4] },
    ],
  },
  {
    id: 46,
    name: 'Weekend Rush',
    starThresholds: [26, 46, 66],
    actors: [
      { characterId: 'louis', requests: [4] },
      { characterId: 'remi', requests: [5] },
      { characterId: 'chloe', requests: [4] },
      { characterId: 'margot', requests: [5, 4] },
      { characterId: 'juliette', requests: [4] },
      { characterId: 'olivier', requests: [5] },
      { characterId: 'marie', requests: [4] },
      { characterId: 'lucas', requests: [5, 4] },
      { characterId: 'manon', requests: [4] },
      { characterId: 'hugo', requests: [5] },
      { characterId: 'lea', requests: [4] },
      { characterId: 'isabelle', requests: [5, 4] },
    ],
  },
  {
    id: 47,
    name: 'Rainy Day',
    starThresholds: [26, 46, 66],
    actors: [
      { characterId: 'vincent', requests: [4] },
      { characterId: 'gabriel', requests: [5] },
      { characterId: 'valerie', requests: [4] },
      { characterId: 'fleur', requests: [5, 4] },
      { characterId: 'raphael', requests: [4] },
      { characterId: 'camille', requests: [5] },
      { characterId: 'pierre', requests: [4] },
      { characterId: 'amelie', requests: [5, 4] },
      { characterId: 'adrien', requests: [4] },
      { characterId: 'nicolas', requests: [5] },
      { characterId: 'nadia', requests: [4] },
      { characterId: 'colette', requests: [5, 4] },
    ],
  },
  {
    id: 48,
    name: 'Market Day',
    starThresholds: [26, 46, 66],
    actors: [
      { characterId: 'antoine', requests: [4] },
      { characterId: 'marcel', requests: [5] },
      { characterId: 'eloise', requests: [4] },
      { characterId: 'jean', requests: [5, 4] },
      { characterId: 'sophie', requests: [4] },
      { characterId: 'theo', requests: [5] },
      { characterId: 'claire', requests: [4] },
      { characterId: 'louis', requests: [5, 4] },
      { characterId: 'remi', requests: [4] },
      { characterId: 'chloe', requests: [5] },
      { characterId: 'margot', requests: [4] },
      { characterId: 'juliette', requests: [5, 4] },
    ],
  },
  {
    id: 49,
    name: 'Festival',
    starThresholds: [26, 46, 66],
    actors: [
      { characterId: 'olivier', requests: [4] },
      { characterId: 'marie', requests: [5] },
      { characterId: 'lucas', requests: [4] },
      { characterId: 'manon', requests: [5, 4] },
      { characterId: 'hugo', requests: [4] },
      { characterId: 'lea', requests: [5] },
      { characterId: 'isabelle', requests: [4] },
      { characterId: 'vincent', requests: [5, 4] },
      { characterId: 'gabriel', requests: [4] },
      { characterId: 'valerie', requests: [5] },
      { characterId: 'fleur', requests: [4] },
      { characterId: 'raphael', requests: [5, 4] },
    ],
  },
  {
    id: 50,
    name: 'Quiet Morning',
    starThresholds: [26, 46, 66],
    actors: [
      { characterId: 'camille', requests: [4] },
      { characterId: 'pierre', requests: [5] },
      { characterId: 'amelie', requests: [4] },
      { characterId: 'adrien', requests: [5, 4] },
      { characterId: 'nicolas', requests: [4] },
      { characterId: 'nadia', requests: [5] },
      { characterId: 'colette', requests: [4] },
      { characterId: 'antoine', requests: [5, 4] },
      { characterId: 'marcel', requests: [4] },
      { characterId: 'eloise', requests: [5] },
      { characterId: 'jean', requests: [4] },
      { characterId: 'sophie', requests: [5, 4] },
    ],
  },
]

export function getLevel(id: number): Level | undefined {
  return LEVELS.find(l => l.id === id)
}

/** Number of customers (NPCs) in a level's session. */
export function customerCount(level: Level): number {
  return level.actors.length
}

/** Number of request stops across all NPCs (how many exclamations appear). */
export function requestCount(level: Level): number {
  return level.actors.reduce((sum, a) => sum + a.requests.length, 0)
}

/** Total questions the player must answer to fully clear a level. */
export function questionCount(level: Level): number {
  return level.actors.reduce((sum, a) => sum + a.requests.reduce((s, q) => s + q, 0), 0)
}

/**
 * Star rating (0-3) for net coins earned in a session.
 * 0 = below the 1-star threshold (level not accomplished).
 */
export function starsForCoins(level: Level, netCoins: number): 0 | 1 | 2 | 3 {
  const [s1, s2, s3] = level.starThresholds
  if (netCoins >= s3) return 3
  if (netCoins >= s2) return 2
  if (netCoins >= s1) return 1
  return 0
}

/**
 * A level is unlocked if it's the first level, or the previous level has
 * been accomplished (at least 1 star).
 */
export function isLevelUnlocked(
  id: number,
  progress: Record<number, LevelProgress> = {},
): boolean {
  if (id <= LEVELS[0].id) return true
  const prev = progress[id - 1]
  return !!prev && prev.stars >= 1
}
