import type { TilesetConfig } from '../types/editor'

// Add your tileset PNGs to /public/tileset/ and declare them here.
export const TILESET_PATHS: TilesetConfig[] = [
  { id: '1_Terrains_and_Fences', src: '/tileset/1_Terrains_and_Fences_32x32.png' },
  { id: '2_City_Terrains', src: '/tileset/2_City_Terrains_32x32.png' },
  { id: '3_City_Props', src: '/tileset/3_City_Props_32x32.png' },
  { id: '4_Generic_Buildings', src: '/tileset/4_Generic_Buildings_32x32.png' },
  { id: '5_Floor_Modular_Buildings', src: '/tileset/5_Floor_Modular_Buildings_32x32.png' },
  { id: '6_Garage_Sales', src: '/tileset/6_Garage_Sales_32x32.png' },
  { id: '7_Villas', src: '/tileset/7_Villas_32x32.png' },
  { id: '8_Worksite', src: '/tileset/8_Worksite_32x32.png' },
  { id: '9_Shopping_Center_and_Markets', src: '/tileset/9_Shopping_Center_and_Markets_32x32.png' },
  { id: '10_Vehicles', src: '/tileset/10_Vehicles_32x32.png' },
  { id: '11_Camping', src: '/tileset/11_Camping_32x32.png' },
  { id: '12_Hotel_and_Hospital', src: '/tileset/12_Hotel_and_Hospital_32x32.png' },
  { id: '13_School', src: '/tileset/13_School_32x32.png' },
  { id: '14_Swimming_Pool', src: '/tileset/14_Swimming_Pool_32x32.png' },
  { id: '15_Police_Station', src: '/tileset/15_Police_Station_32x32.png' },
  { id: '16_Office', src: '/tileset/16_Office_32x32.png' },
  { id: '17_Garden', src: '/tileset/17_Garden_32x32.png' },
  { id: '18_Fire_Station', src: '/tileset/18_Fire_Station_32x32.png' },
  { id: '19_Graveyard', src: '/tileset/19_Graveyard_32x32.png' },
  { id: '20_Subway_and_Train_Station', src: '/tileset/20_Subway_and_Train_Station_32x32.png' },
  { id: '21_Beach', src: '/tileset/21_Beach_32x32.png' },
  { id: '22_Post_Office', src: '/tileset/22_Post_Office_32x32.png' },
  { id: '23_Military_Base', src: '/tileset/23_MIlitary_Base_32x32.png' },
  { id: '24_Additional_Houses', src: '/tileset/24_Additional_Houses_32x32.png' },
  { id: 'Modern_Exteriors_Complete', src: '/tileset/Modern_Exteriors_Complete_Tileset_32x32.png' },
]
